# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Mindvault',
                'doc_host': 'https://Vedmani.github.io',
                'git_url': 'https://github.com/Vedmani/Mindvault',
                'lib_path': 'Mindvault'},
  'syms': {'Mindvault.core': {'Mindvault.core.foo': ('core.html#foo', 'Mindvault/core.py')}}}
